#!/bin/bash

#########################################################
#########################################################
##### ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗ #####
##### ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║ #####
##### ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║ #####
##### ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║ #####
##### ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║ #####
##### ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝ #####
#########################################################
#########################################################

killall sxhkd unclutter &
wait
sxhkd &
.config/polybar/launch.sh &
picom &
unclutter --timeout 5 &
xrandr --output eDP1 --node 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off &
pulseaudio -D &
xsetroot -cursor_name left_ptr &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           12

wal -R &
. "${HOME}/.cache/wal/colors.sh"

bspc config active_border_color "$color1"
bspc config normal_border_color "$color2"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color4"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
